import { AuthProvider } from "./context/AuthContext";
import Navbar from "./components/Navbar"; 
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Seahawk Vault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <Navbar /> {/* Navbar access to AuthContext */}
          {children} {/* Page content access to AuthContext */}
        </AuthProvider>
      </body>
    </html>
  );
}
